#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-Tv-Sweden-TvDotNu
version:      1.01
version_from: TvDotNu.pm
installdirs:  site
requires:
    HTML::Parser:                  3.26
    LWP::UserAgent:                2
    HTTP::Request:                 1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
